[package]
name = "rdiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
adler32 = "1.2.0"
sha3 = "0.10.4"
serde = { version = "1.0.143", features = ["derive"] }
bincode = "1.3.3"
multimap = "0.8.3"